[package]
name = "hashcash_example"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { version = "0.4", features = ["std"] }
sha256 = "1.5.0"
primitive-types = "0.13.1"
num-bigint = "0.4"
num-traits = "0.2"
